- name: docker build and push
  hosts: local  # Replace with the hostname or IP address of your target server
  become: yes  # Run tasks with sudo privileges
  vars:
    ansible_python_interpreter: /usr/bin/python3 

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes   

    - name: Build Docker Image
      command: docker build -t petstore .
      args:
        chdir: /var/lib/jenkins/workspace/petstore

    - name: tag image
      command: docker tag petstore:latest mathewf/petstore:latest 

    - name: Log in to Docker Hub
      docker_login:
        registry_url: https://index.docker.io/v1/
        username: mathew.francis@indiumsoft.com
        password: dckr_pat_CI_icVkceRnH-yd-cKAKcsoH6y0
      ignore_errors: yes

    - name: Push image
      command: docker push mathewf/petstore:latest

    - name: Run container
      command: docker run -d --name pet1 -p 8081:8080 mathewf/petstore:latest
